<?xml version="1.0" encoding="utf-8"?><Database Name="HumaneSociety" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JLOR-ASUS;Initial Catalog=HumaneSociety;Integrated Security=True" SettingsObjectName="HumaneSociety.Properties.Settings" SettingsPropertyName="HumaneSocietyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="jl.Adopter" Member="Adopters">
    <Type Name="Adopter">
      <Column Name="Adopter_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Animal_Category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Animal_Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Animal_Age" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="jl.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="Room_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Room_Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Room_Animal" Member="Animals" ThisKey="Room_Id" OtherKey="Room_Id" Type="Animal" />
    </Type>
  </Table>
  <Table Name="jl.Animal" Member="Animals">
    <Type Name="Animal">
      <Column Name="Animal_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Shots" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Food" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Room_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Room_Animal" Member="Room" ThisKey="Room_Id" OtherKey="Room_Id" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
</Database>